[default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.13"
optimizer = true
optimizer_runs = 20000
gas_reports = ["*"]



# More config options: https://github.com/gakonst/foundry/tree/master/config